// Run with: node _gen_europe_map.js
// Extracts European country paths from world.svg → files/europe-map.js
const fs = require('fs');
const src = fs.readFileSync('files/world.svg', 'utf8');

const EU_IDS = new Set([
  'AL','AT','BA','BE','BG','BY','CH','CY','CZ','DE','DK','EE','ES','FI','FO',
  'FR','GB','GR','HR','HU','IE','IS','IT','LT','LU','LV','MA','MD','ME','MK',
  'MT','NL','NO','PL','PT','RO','RS','SE','SI','SK','TN','TR','UA','XK',
]);

// Map class="Name" → ISO code for large/multi-part countries in this SVG
const CLS_TO_ISO = {
  'France': 'FR', 'United Kingdom': 'GB', 'Italy': 'IT', 'Turkey': 'TR',
  'Norway': 'NO', 'Denmark': 'DK', 'Sweden': 'SE', 'Finland': 'FI',
  'Greece': 'GR', 'Ireland': 'IE', 'Germany': 'DE',
};

let paths = '';
// Match every <path ...> or <path ...></path>
const re = /<path\b([^>]*)>(\s*<\/path>)?/gs;
let m;
while ((m = re.exec(src)) !== null) {
  const attrs = m[1];
  const idM   = attrs.match(/\bid="([^"]+)"/);
  const clsM  = attrs.match(/\bclass="([^"]+)"/);
  const id    = idM  ? idM[1]  : '';
  const cls   = clsM ? clsM[1] : '';
  // Determine ISO code for this path
  const iso = (EU_IDS.has(id) ? id : null) || CLS_TO_ISO[cls] || null;
  if (!iso) continue;
  // Rebuild path with data-country, remove id/class friction
  const dM = attrs.match(/\bd="([^"]+)"/);
  if (!dM) continue;
  paths += `<path data-country="${iso}" d="${dM[1]}"/>\n`;
}

const svgStr = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="855 48 480 335">\n${paths}</svg>`;

const lines = paths.trim().split('\n').length;
console.log(`Extracted ${lines} path elements`);

const out = `/* Auto-generated by _gen_europe_map.js — do not edit */\nconst EUROPE_SVG_STR = ${JSON.stringify(svgStr)};\n`;
fs.writeFileSync('files/europe-map.js', out, 'utf8');
console.log('Written files/europe-map.js');
